window.EXERCISES = [
  {id:'jumping-jacks',name:'Jumping Jacks',emoji:'🤸',level:'beginner',goals:['stay-active','weight-loss'],type:'cardio',duration:60,reps:null,video:'https://www.youtube.com/embed/c4DAnQ6DtF8',instructions:['Stand tall with feet together.','Jump feet apart while raising arms overhead.','Return softly to the start.'],mistakes:['Landing too hard','Locking the knees'],alternatives:['marching-in-place']},
  {id:'squat',name:'Bodyweight Squat',emoji:'🏋️',level:'beginner',goals:['stay-active','build-strength','weight-loss'],type:'strength',duration:null,reps:12,video:'https://www.youtube.com/embed/YaXPRqUwItQ',instructions:['Stand with feet about shoulder-width apart.','Sit hips back and bend the knees comfortably.','Keep chest lifted and stand back up.'],mistakes:['Knees collapsing inward','Rounding the back'],alternatives:['chair-squat']},
  {id:'push-up',name:'Push-up',emoji:'💪',level:'intermediate',goals:['build-strength','stay-active'],type:'strength',duration:null,reps:10,video:'https://www.youtube.com/embed/IODxDxX7oi4',instructions:['Place hands below shoulders.','Keep body in a straight line.','Lower with control and press back up.'],mistakes:['Sagging hips','Flaring elbows excessively'],alternatives:['knee-push-up','wall-push-up']},
  {id:'plank',name:'Plank',emoji:'🧘',level:'beginner',goals:['build-strength','improve-posture','stay-active'],type:'strength',duration:30,reps:null,video:'https://www.youtube.com/embed/pSHjTRCQxIw',instructions:['Place forearms below shoulders.','Keep a comfortable straight body line.','Breathe steadily.'],mistakes:['Hips dropping','Holding breath'],alternatives:['knee-plank']},
  {id:'lunges',name:'Reverse Lunges',emoji:'🦵',level:'beginner',goals:['build-strength','stay-active'],type:'strength',duration:null,reps:10,video:'https://www.youtube.com/embed/QOVaHwm-Q6U',instructions:['Step one foot back.','Lower under control.','Push through the front foot to return.'],mistakes:['Leaning too far forward','Moving too quickly'],alternatives:['supported-lunge']},
  {id:'cat-cow',name:'Cat-Cow Stretch',emoji:'🐈',level:'beginner',goals:['improve-flexibility','improve-posture'],type:'stretch',duration:60,reps:null,video:'https://www.youtube.com/embed/kqnua4rHVVA',instructions:['Start on hands and knees.','Move gently between rounded and extended positions.','Keep movement comfortable.'],mistakes:['Forcing range of motion'],alternatives:[]},
  {id:'shoulder-roll',name:'Shoulder Rolls',emoji:'🔄',level:'beginner',goals:['improve-flexibility','improve-posture'],type:'stretch',duration:45,reps:null,video:'https://www.youtube.com/embed/ZxKEvBErx9A',instructions:['Stand or sit tall.','Roll shoulders slowly backward.','Keep breathing relaxed.'],mistakes:['Moving too fast'],alternatives:[]},
  {id:'marching-in-place',name:'March in Place',emoji:'🚶',level:'beginner',goals:['stay-active'],type:'cardio',duration:60,reps:null,video:'',instructions:['Stand tall.','Lift one knee at a time.','Move at a comfortable pace.'],mistakes:['Leaning backward'],alternatives:['jumping-jacks']},
  {id:'wall-push-up',name:'Wall Push-up',emoji:'🧱',level:'beginner',goals:['build-strength','stay-active'],type:'strength',duration:null,reps:12,video:'',instructions:['Face a wall with hands at chest height.','Bend elbows and move toward wall.','Push back gently.'],mistakes:['Shrugging shoulders'],alternatives:['knee-push-up']},
  {id:'chair-squat',name:'Chair Squat',emoji:'🪑',level:'beginner',goals:['build-strength','stay-active'],type:'strength',duration:null,reps:10,video:'',instructions:['Stand in front of a stable chair.','Lower under control toward the seat.','Stand back up.'],mistakes:['Dropping quickly'],alternatives:['squat']}
];